### ISSUE TITLE
lucky command not found

### ISSUE THREAD

**Issue by amiceli** [luckyframework/migrator#2]
Maybe I missed something but when I run `lucky gen.migration CreateUsers` I got a command not found error.

Thanks.

**Comment by paulcsmith** [comment]
@amiceli This is still very much a WIP, but it may be because you do not have the Lucky CLI. You can install it with https://github.com/luckyframework/cli#installing-the-cli

There are still a few things that need to be done with the generators, but that should at least get you started! LMK if you run into anything else

**Comment by paulcsmith** [comment]
Also until this is fixed (https://github.com/luckyframework/migrator/issues/3) you'll need to make sure you have a `db/migrations` folder already created or it will error
