### ISSUE TITLE
Extract `add_index` to it's own helper method that can be used outside create/alter

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/migrator#27]
Instead of this: 

https://github.com/luckyframework/migrator/blob/cd0fcaa195a2211e5b10f851610bc4707be57cb5/src/lucky_migrator/create_table_statement.cr#L82-L85

Let's move it to it's own helper in `StatementHelper` so it can be used outside create/alter https://github.com/luckyframework/migrator/blob/master/src/lucky_migrator/statement_helpers.cr

**Comment by mikeeus** [comment]
```crystal
  def migrate
    create :users do
      add email : String
    end

    add_index :users, :email
  end
```
And defined like:
```crystal
module LuckyMigrator::StatementHelpers
  ...
  def add_index(table_name : Symbol, column : Symbol, unique = false, using : Symbol = :btree)
    execute CreateIndexStatement.new(table_name, column, using, unique).build
  end
```
In this case, inline indexes created by CreateTableStatements can't check for duplicates. So if you do something like this it throws an error:

```crystal
  def migrate
    create :users do
      add email : String, index: true
    end

    add_index :users, :email, unique: true
  end
# => relation "users_email_index" already exists
```
But when you try to rollback it says "Did nothing. No migration to roll back.", and when you try to migrate it says "relation "users" already exists". This is because the error is thrown in the `migrate` call before `track_migration`:
https://github.com/luckyframework/migrator/blob/cd0fcaa195a2211e5b10f851610bc4707be57cb5/src/lucky_migrator/migration.cr#L22-L30

Maybe transactions will fix this, or we need to keep track of statements in the Helpers class and remove duplicates.

I'll push it up as is, and you can tell me how to proceed.

**Comment by paulcsmith** [comment]
Ah I see what you mean. Yes transactions will fix this because when it fails to migrate it will rollback automatically. Then you can fix it and it will migrate again. Thanks for the in-depth explanation. That was super helpful.

For now we can move forward with it as-is and people will just have to be careful with migrations until transactions are used

**Comment by mikeeus** [comment]
Great, that's a relief. I was worried we need to track statements and check for errors, etc.
